### ISSUE TITLE
Make table decision name / ID editing more obvious

### ISSUE THREAD

**Issue by nikku** [bpmn-io/dmn-js#168]
Right now it is hard for a user to understand that the name / id of a decision can be edited in the top left corner of the diagram. It is also not clear what is Name (Label) and ID (Technical Data)

I propose the following improvements:

* showing the outline of an input during hover / editing
* Show the ID as monospace to denote "technical stuff". I think that is a common notation that will help making these things more obvious
* Add always visible outline to both elements to make the function of the element more aparent.

__Demo__

![image](https://cloud.githubusercontent.com/assets/58601/20346646/84a6b024-abfd-11e6-8559-643e80362868.png)

The following `less` snippet would make things work during editing:

```less

.dmn-definitions {
  position: absolute;
  top: 20px;
  left: 80px;
  background: #FAFAFA;
  color: #000;
  padding: 5px;
  border-radius: 3px;

  opacity: .6;
  transition: opacity .3;

  &:hover,
  &:focus {
    opacity: 1;
  }

  > .editable {
    padding: 5px;
    padding-bottom: 4px;
    outline: none;

    &:hover,
    &:focus {
      padding: 4px;
      padding-bottom: 3px;
    }
  }

  > .dmn-definitions-id {
    margin-top: 2px;
    font-family: monospace;
  }
}
```
