### ISSUE TITLE
I can add a description

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js#239]
* [x] Descriptions can be added via `contextmenu` -> `add description` (this shows and focuses the description box) 

* [x] Cells with a description show little description indicator:

    ```css
    .dmn-decision-table-container .description-indicator {
      position: absolute;
      top: 0;
      right: -4px;
      border-left: 4px solid transparent;
      border-right: 4px solid transparent;
      border-bottom: 4px solid black;
      transform: rotate(45deg);
      transform-origin: top;
    }
    ```

* [x] Description is shown on cell click and hides on cell unfocus
* [x] Removing description text unsets the description on description box close
