### ISSUE TITLE
DRD: Cursor skips to beginning of definitions name on SPACE

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/dmn-js#274]
![foobar](https://user-images.githubusercontent.com/7633572/33719497-3a080f10-db61-11e7-8f79-0661009d5673.gif)

**Comment by eugene-moroz** [comment]
Also occurred in DMN editor.

**Comment by pinussilvestrus** [comment]
How can I enable this definitions edit popup in the DRD? Is this possible in newer Modeler versions at all?

**Comment by philippfromme** [comment]
We've hidden it with the introduction of the DMN properties panel by adding

```css
.djs-container > .dmn-definitions {
    display: none;
  }
```

to the stylesheet of the DMN editor.
